CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,telegram_id BIGINT NOT NULL UNIQUE,username TEXT,first_name TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS clubs(id BIGSERIAL PRIMARY KEY,owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL UNIQUE,short_name TEXT NOT NULL,logo TEXT,stadium_name TEXT NOT NULL,stadium_level INT NOT NULL DEFAULT 1 CHECK(stadium_level BETWEEN 1 AND 20),budget BIGINT NOT NULL DEFAULT 20000000 CHECK(budget>=0),fans INT NOT NULL DEFAULT 5000 CHECK(fans>=0),reputation INT NOT NULL DEFAULT 1 CHECK(reputation>=1),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS players(id BIGSERIAL PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT NOT NULL,nationality CHAR(3) NOT NULL,age INT NOT NULL CHECK(age BETWEEN 16 AND 40),position TEXT NOT NULL CHECK(position IN ('GK','CB','LB','RB','DM','CM','AM','LW','RW','ST')),pace INT NOT NULL CHECK(pace BETWEEN 1 AND 100),shooting INT NOT NULL CHECK(shooting BETWEEN 1 AND 100),passing INT NOT NULL CHECK(passing BETWEEN 1 AND 100),dribbling INT NOT NULL CHECK(dribbling BETWEEN 1 AND 100),defending INT NOT NULL CHECK(defending BETWEEN 1 AND 100),physical INT NOT NULL CHECK(physical BETWEEN 1 AND 100),stamina INT NOT NULL CHECK(stamina BETWEEN 1 AND 100),mental INT NOT NULL CHECK(mental BETWEEN 1 AND 100),market_value BIGINT NOT NULL,salary BIGINT NOT NULL,potential INT NOT NULL CHECK(potential BETWEEN 1 AND 100));
CREATE TABLE IF NOT EXISTS club_players(id BIGSERIAL PRIMARY KEY,club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,player_id BIGINT NOT NULL REFERENCES players(id),shirt_number INT,contract_until DATE,fitness INT NOT NULL DEFAULT 100 CHECK(fitness BETWEEN 0 AND 100),form INT NOT NULL DEFAULT 0 CHECK(form BETWEEN -2 AND 2),is_injured BOOLEAN NOT NULL DEFAULT FALSE,injury_matches INT NOT NULL DEFAULT 0 CHECK(injury_matches>=0),UNIQUE(club_id,player_id));
CREATE TABLE IF NOT EXISTS leagues(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,invite_code TEXT NOT NULL UNIQUE,creator_user_id BIGINT NOT NULL REFERENCES users(id),status TEXT NOT NULL DEFAULT 'WAITING' CHECK(status IN ('WAITING','ACTIVE','FINISHED')),max_teams INT NOT NULL CHECK(max_teams BETWEEN 4 AND 12),current_round INT NOT NULL DEFAULT 0,total_rounds INT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS league_teams(league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,played INT NOT NULL DEFAULT 0,wins INT NOT NULL DEFAULT 0,draws INT NOT NULL DEFAULT 0,losses INT NOT NULL DEFAULT 0,goals_for INT NOT NULL DEFAULT 0,goals_against INT NOT NULL DEFAULT 0,points INT NOT NULL DEFAULT 0,PRIMARY KEY(league_id,club_id));
CREATE TABLE IF NOT EXISTS matches(id BIGSERIAL PRIMARY KEY,league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,round INT NOT NULL,home_club_id BIGINT NOT NULL REFERENCES clubs(id),away_club_id BIGINT NOT NULL REFERENCES clubs(id),home_score INT,away_score INT,home_xg NUMERIC(4,2),away_xg NUMERIC(4,2),seed BIGINT NOT NULL,status TEXT NOT NULL DEFAULT 'SCHEDULED' CHECK(status IN ('SCHEDULED','LIVE','FINISHED')),started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS match_lineups(id BIGSERIAL PRIMARY KEY,match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,club_id BIGINT NOT NULL REFERENCES clubs(id),player_id BIGINT NOT NULL REFERENCES players(id),position TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'STARTER',is_starting BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS match_tactics(id BIGSERIAL PRIMARY KEY,match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,club_id BIGINT NOT NULL REFERENCES clubs(id),formation TEXT NOT NULL,style TEXT NOT NULL,tempo INT NOT NULL,pressing INT NOT NULL,width INT NOT NULL,defensive_line INT NOT NULL,aggression INT NOT NULL);
CREATE TABLE IF NOT EXISTS match_events(id BIGSERIAL PRIMARY KEY,match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,minute INT NOT NULL,event_type TEXT NOT NULL,club_id BIGINT,player_id BIGINT,secondary_player_id BIGINT,description TEXT NOT NULL,metadata JSONB NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS transfers(id BIGSERIAL PRIMARY KEY,player_id BIGINT NOT NULL REFERENCES players(id),from_club_id BIGINT,to_club_id BIGINT,price BIGINT NOT NULL CHECK(price>=0),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_matches_league_round ON matches(league_id,round);CREATE INDEX IF NOT EXISTS idx_events_match_minute ON match_events(match_id,minute);CREATE INDEX IF NOT EXISTS idx_club_players_club ON club_players(club_id);

CREATE TABLE IF NOT EXISTS club_tactics(
 club_id BIGINT PRIMARY KEY REFERENCES clubs(id) ON DELETE CASCADE,
 formation TEXT NOT NULL DEFAULT '4-3-3', style TEXT NOT NULL DEFAULT 'BALANCE',
 tempo INT NOT NULL DEFAULT 50, pressing INT NOT NULL DEFAULT 50, width INT NOT NULL DEFAULT 50,
 defensive_line INT NOT NULL DEFAULT 50, aggression INT NOT NULL DEFAULT 50
);
CREATE TABLE IF NOT EXISTS club_lineups(
 club_id BIGINT PRIMARY KEY REFERENCES clubs(id) ON DELETE CASCADE,
 player_ids BIGINT[] NOT NULL DEFAULT '{}'
);
CREATE UNIQUE INDEX IF NOT EXISTS one_owner_per_player ON club_players(player_id);

CREATE TABLE IF NOT EXISTS club_player_instructions(
 id BIGSERIAL PRIMARY KEY, club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
 player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
 role TEXT NOT NULL DEFAULT 'STARTER', instruction TEXT NOT NULL DEFAULT 'BALANCED',
 board_x INT NOT NULL DEFAULT 50, board_y INT NOT NULL DEFAULT 50,
 UNIQUE(club_id,player_id)
);
CREATE TABLE IF NOT EXISTS match_player_instructions(
 id BIGSERIAL PRIMARY KEY, match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
 club_id BIGINT NOT NULL REFERENCES clubs(id), player_id BIGINT NOT NULL REFERENCES players(id),
 role TEXT NOT NULL, instruction TEXT NOT NULL, board_x INT NOT NULL, board_y INT NOT NULL
);

