ALTER TABLE players ADD COLUMN IF NOT EXISTS rarity TEXT NOT NULL DEFAULT 'BASE' CHECK(rarity IN ('BASE','RARE','EPIC','LEGENDARY'));
ALTER TABLE players ADD COLUMN IF NOT EXISTS card_version TEXT NOT NULL DEFAULT 'STANDARD';
ALTER TABLE players ADD COLUMN IF NOT EXISTS real_player BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS preferred_foot TEXT NOT NULL DEFAULT 'R' CHECK(preferred_foot IN ('L','R'));
ALTER TABLE players ADD COLUMN IF NOT EXISTS secondary_positions TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE players ADD COLUMN IF NOT EXISTS portrait_url TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS data_source TEXT NOT NULL DEFAULT 'generated';
CREATE INDEX IF NOT EXISTS idx_players_rarity ON players(rarity);
CREATE INDEX IF NOT EXISTS idx_players_market ON players(market_value DESC);
