ALTER TABLE matches ADD COLUMN IF NOT EXISTS live_phase TEXT NOT NULL DEFAULT 'SCHEDULED' CHECK(live_phase IN ('SCHEDULED','FIRST_HALF','HALFTIME','SECOND_HALF','FINISHED'));
ALTER TABLE matches ADD COLUMN IF NOT EXISTS phase_started_at TIMESTAMPTZ;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS halftime_ends_at TIMESTAMPTZ;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS second_half_started_at TIMESTAMPTZ;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS second_half_data JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS live_event_cursor BIGINT NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_matches_live_phase ON matches(status,live_phase,phase_started_at);
